### PR TITLE
Update package index

### PR DESCRIPTION
**Pull request by awvwgk**
new packages:

- [fortran-curl](https://github.com/interkosmos/fortran-curl)
- [FKB](https://github.com/scientific-computing/FKB)
- [hipfort](https://github.com/ROCmSoftwarePlatform/hipfort)
- [fpm](https://github.com/fortran-lang/fpm)
- [flibcpp](https://github.com/swig-fortran/flibcpp)
- [camfort](https://github.com/camfort/comfort)
- [findent](https://https://sourceforge.net/projects/findent/)
- [fprettify](https://github.com/pseewald/fprettify)
- [shroud](https://github.com/LLNL/shroud)
- [swig-fortran](https://github.com/swig-fortran/swig)
- [f90wrap](https://github.com/jameskermode/f90wrap)

updates packages:

- sqliteff, elsi, vegetables, erloff, tapenade, strff, iso_varying_string, fortjson, fortran-csv-module, openmolcas, octopus, WHIZARD, MESA, Truchas, quaff, psblas3, ElmerFEM, ogpf, jsonff, parff

new features:

- use https://badgen.net/ for gitlab badges

### CODE REVIEW

**Review by LKedward — APPROVED** [review]
This is really great @awvwgk, thanks! Changes all look good to me :+1:

**Comment by LKedward** [comment]
#build_preview

**Comment by LKedward** [comment]
Hi @awvwgk, are you able to check the effect of these changes on the package search functionality? I think the Gitlab projects now need special attention in the Javascript search.

<https://github.com/fortran-lang/fortran-lang.org/blob/f3ea348612f944de4c396b05aab9a970a9dd6cfb/assets/js/package_search.js#L112-L162>

**Comment by awvwgk** [comment]
Seems the search is still finding results, see https://fortran-lang.org/pr/196/packages/search/?query=strff, but not generating the correct links.

**Comment by LKedward** [comment]
> Seems the search is still finding results, see https://fortran-lang.org/pr/196/packages/search/?query=strff, but not generating the correct links.

Yep, and it would be nice to retain the Gitlab icons as well :+1:

**Comment by awvwgk** [comment]
I got the search working with 8623b32877bad348e16c6a238129db21d5b6b948, somewhat tricky to find all the right places to add a new field, but now it seems fine.

**Comment by awvwgk** [comment]
#build_preview

**Comment by awvwgk** [comment]
#delete_preview

**Comment by awvwgk** [comment]
I added a bunch more of packages, mainly formatters I have recommended recently to colleagues and the interface generators discussed on the discourse.

**Pull request merged**
