### PR TITLE
Fix: minor typo on compilers page.

### PR DESCRIPTION
**Pull request by LKedward**
This small PR will test PR preview functionality.

### CODE REVIEW

**Comment by LKedward** [comment]
#build_preview

**Comment by LKedward** [comment]
#build_preview

**Comment by certik** [comment]
@LKedward thanks for setting it up! Note that it does not seem to work, the PR link shows the website with the word "Discountinued", which you fixed in this PR.

**Comment by milancurcic** [comment]
Hmm, seems to me like it works--both link here and link on the preview website.

**Comment by LKedward** [comment]
> @LKedward thanks for setting it up! Note that it does not seem to work, the PR link shows the website with the word "Discountinued", which you fixed in this PR.

Yep you are right - the action is not checking out the right commit, currently looking for a solution.

**Comment by certik** [comment]
@milancurcic it does not work for me, see the screenshot:

Screenshot from 2020-05-07 10-41-35

**Comment by milancurcic** [comment]
Got it, nevermind, I totally misunderstood.

**Comment by LKedward** [comment]
#build_preview

**Comment by LKedward** [comment]
#build_preview

**Comment by LKedward** [comment]
this is the one...
#build_preview

**Comment by LKedward** [comment]
Okay, I think this is finally working!
@milancurcic and @certik apologies for the large number of notifications you have probably received in the last hour!
Last thing to test is that both of you can also trigger a build by commenting '#build_preview'.

**Comment by milancurcic** [comment]
#build_preview

**Comment by certik** [comment]
I think it's working! Thanks for fixing it @LKedward.

**Comment by LKedward** [comment]
#delete_preview

**Pull request merged**
