### PR TITLE
Fix build preview

### PR DESCRIPTION
**Pull request by awvwgk**
- use new syntax to set environment variables

### CODE REVIEW

**Comment by awvwgk** [comment]
#build_preview

**Comment by awvwgk** [comment]
This is still using the workflow file from the main repo rather than from this branch. Seems like the event triggering the build preview through a comment is not associated with the PR but with the latest commit on the main branch instead?

So you have to trust me that this will fix the issue with the build preview :wink:

**Review by LKedward — APPROVED** [review]
Thanks @awvwgk, this all looks good 👍

**Review by milancurcic — APPROVED** [review]
Thank you!

**Comment by urbanjost** [comment]
#build preview

**Pull request merged**
