### PR TITLE
Newsletter May 2022

### PR DESCRIPTION
**Pull request by milancurcic**
Here's the newsletter draft:

* [x] Draft text
* [x] GitHub stats data
* [x] Flang updates by @AlexisPerry
* [x] LFortran updates by @certik @czgdp1807 or @HaoZeke 

Let's plan to merge by Friday, May 6.

Thank you!

### CODE REVIEW

**Comment by AlexisPerry** [comment]
Please see https://github.com/milancurcic/fortran-lang.github.io/pull/7 for Flang updates.  Thanks!

**Comment by gnikit** [comment]
@milancurcic would you like me to write a short announcement in May's newsletter for Modern Fortran migrating to fortran-lang?

**Comment by milancurcic** [comment]
@gnikit yes, please! I forgot about that. I think best to add it as a bullet point under events. Feel free to commit directly to this PR branch and add your name to the authors list. Thank you!

**Comment by gnikit** [comment]
Done, I was unable to push to your branch so I opened a separate PR. I hope that's okay.

**Comment by certik** [comment]
@czgdp1807, @HaoZeke is one of you able to put in LFortran updates?

**Comment by czgdp1807** [comment]
I can do it tonight (my time) i.e., in 3 hours.

**Comment by czgdp1807** [comment]
Done. See the LFortran updates in https://github.com/milancurcic/fortran-lang.github.io/pull/9

**Comment by milancurcic** [comment]
Thanks all! We have all the updates now. Let's merge later today if there are no objections.

**Pull request merged**
