### PR TITLE
Add PROPACK to package index

### PR DESCRIPTION
**Pull request by ivan-pi**
Addresses a subtask in https://github.com/fortran-lang/fortran-lang.org/issues/232

Project homepage: http://sun.stanford.edu/~rmunk/PROPACK/

[PROPACK was recently added to SciPy](https://github.com/scipy/scipy/releases) as one of the available SVD solvers.

Note pencil-code, Elk, and librsb, are handled in other pull requests.

### CODE REVIEW

**Review by kjelljorner — APPROVED** [review]
Looks good to me, although I don't really understand why the changes for the related pull requests need to be included in this one. I would rather prefer separate pull requests with the unique changes in each.

**Comment by ivan-pi** [comment]
That's a valid point. My mind was just not thinking clearly enough to roll back from a new branch...

**Comment by LKedward** [comment]
#build_preview

**Review by LKedward — APPROVED** [review]
LGTM 👍 Thanks Ivan!

**Comment by LKedward** [comment]
#delete_preview

**Pull request merged**
