### PR TITLE
add CI for publishing on the fortran-lang twitter account upon merging a certain PR

### PR DESCRIPTION
**Pull request by p-costa**
Hello everyone!

As discussed in the [fortran-lang discourse](https://fortran-lang.discourse.group/t/tool-to-manage-tweets/322?u=pcosta), this PR implements a CI that:

1. Generates tweets by commenting on a PR
2. Publishes these tweets when the PR is merged

Please have a look, and feel free to test it by submitting a PR in this repo I created: [p-costa/piu-piu-sandbox](https://github.com/p-costa/piu-piu-sandbox).

If you are happy with it, to get it to work, one needs to create a twitter app, following the steps similar to those indicated here: [github.com/gr2m/twitter-together/blob/master/docs/01-create-twitter-app.md](https://github.com/gr2m/twitter-together/blob/master/docs/01-create-twitter-app.md) and add the corresponding keys and tokens to this repo.

I should thank the author of [find-comment](https://github.com/peter-evans/find-comment) for very promptly considering issues [#23](https://github.com/peter-evans/find-comment/issues/23) and [#24](https://github.com/peter-evans/find-comment/issues/24).

The tweets are published using [send-tweet-action](https://github.com/marketplace/actions/send-tweet-action), as per @LKedward suggestion.

__It works as follows:__

A comment in the PR starting with the keyword #tweet `text` will:
1. remove a previous tweet, if it exists.
2. add a new tweet to be published by the CI once the PR is merged.

A comment in the PR starting with the keyword #untweet will remove the tweet.

Then, when the PR is merged, the CI will look for a specific keyword (__[tweet]__) published by the GitHub actions bot, and, if it exists in the PR comment thread, it will be deployed for publication in the fortran-lang twitter account.

### CODE REVIEW

**Comment by LKedward** [comment]
Amazing, great work @p-costa! I'll have a look through this later today.

**Comment by certik** [comment]
Great work. I tested it a bit.

Here are my questions:

https://github.com/p-costa/piu-piu-sandbox/pull/1#issuecomment-703616971

**Comment by p-costa** [comment]
Thanks for creating the PR and testing it @certik . I should have mentioned here as well that:

#tweet `text` will:

1. remove a previous tweet, if it exists.
2. add a new tweet to be published by the CI once the PR is merged.

#untweet will remove the tweet.

**Comment by milancurcic** [comment]
Thanks, @p-costa! I have 2 questions:

* Considering that `#tweet text` will remove a previous tweet if it exists, that means that there can be only one Tweet per PR, correct?
* What happens if `text` exceeds 280 characters? Do we get a thread of tweets or is the tweet truncated (or something else)?

**Comment by p-costa** [comment]
Hi @milancurcic , 

* Correct. I assumed that one will not be tweeting too much from here, so 1 tweet per merged PR sounded reasonable.
* The CI always prints a preview of the tweet showing the character count. So if it is exceeded one will see it and can fix it before merging.

**Comment by p-costa** [comment]
I converted this to draft so that I can polish the implementation tomorrow and make some final tests. Feel free to review it in any case, as it should not change much from my side.

**Comment by p-costa** [comment]
Just want to comment here that it's ready. But no rush from my side -- I understand that this being a small convenience shouldn't be a high priority thing.

**Review by LKedward — APPROVED** [review]
Great stuff! I don't see any issues with the workflow which has already been tested and demonstrated. Clearly some work is still required to link to the twitter account.

It looks like anyone can create and modify a tweet, but only maintainers can merge and publish the tweet so I think this workflow works well. Thanks @p-costa :+1:

**Comment by certik** [comment]
+1 with me also

**Comment by p-costa** [comment]
> It looks like the homework for me is to set up the app and keys:

Let me know if you run into problems. One thing that was not written in the instructions and I had to do was making sure that the app as read *and write* permissions:

example

**Comment by milancurcic** [comment]
Okay, this is now done. I set the secrets in the Org and allowed them to be shared with this repo. This way we can easily reuse them in other repos when we want.

Should this now be merged?

**Pull request merged**
