### PR TITLE
Correct license identifiers

### PR DESCRIPTION
**Pull request by awvwgk**
`license: none` should be a no-go for the package index. The package index is of course no legal advice for licensing, but the information should be as accurate as possible. A package without license is unusable by definition (for open source projects), which is unfair to packages with permissive licensing conditions.
For a simple summary see: https://choosealicense.com/no-permission/

I went through all the packages with `license: none` and tried to identify the licenses. I also tried to correct all licenses which are not valid SPDX license identifiers. Many missing licenses were malformatted BSD or MIT licenses, but some had actually interesting licensing condition like original MIT license with changes under BSD-3-Clause and so on.

There are still some issues with the GPL-2.0, and GPL-3.0, which should have the `-only` or `-or-later` suffix. (L)GPL-2 and (L)GPL-3 is usually insufficient to identify the license of a package clearly, since the minor version is missing.

This PR is open for discussion.

### CODE REVIEW

**Review by certik — APPROVED** [review]
Awesome, thanks a lot. I agree license "none" is a no-no.

**Comment by awvwgk** [comment]
Many of @szaghi's projects have a GPL-3.0-only OR BSD-2-Clause OR BSD-3-Clause OR MIT license, which is quite lengthy for a badge (it doesn't state GPL-3.0-or-later for any package, I think). Not sure how to put those correctly without overflowing the rows.

**Comment by LKedward** [comment]
Thanks @awvwgk, I agree with you however please note that `license: none` is a (misleading) programmatic identifier to disable rendering of the shields.io badge, it __does not indicate anywhere on site that any software is license-free__. 
Our package guidelines already state that only open source projects are accepted and they also require that the license field be specified if not detectable by github. I believe the large number of `license: none` entries may be, as you point out, that the licenses were non-standard formatting which meant I didn't know which identifier to use - at the time I opted to display no information rather than wrong information.
Thank you for tracking down this information.

We never made any promises regarding the use of SPDX identifiers, but I have no objection to adopting them now.

**Comment by awvwgk** [comment]
> I agree with you however please note that `license: none` is a (misleading) programmatic identifier to disable rendering of the shields.io badge, it does not indicate anywhere on site that any software is license-free.

How about `license: off` which should map to a boolean false in yaml, has a much clearer indent and can easily used within liquid. Or you can have a separate field as `display-license: false` to avoid mixing the meta data with programmatic identifiers.

**Comment by LKedward** [comment]
Are there still packages currently in the index where we still need this capability? If so, a separate field seems like the best option. If not, the behaviour should simply be removed. It already isn't allowed in future PRs according to the current guidelines.

**Comment by awvwgk** [comment]
This sounds way better than my suggestion :+1:.

**Comment by certik** [comment]
Thanks for fixing this. Looks like there is no opposition, so I am going to merge it.

**Pull request merged**
