### PR TITLE
List FPM registry packages

### PR DESCRIPTION
**Pull request by LKedward**
A minimal modification to include packages from fpm-registry on the website.
They are listed in their own category ('fpm') as well as searchable via the existing search function.

This is a stopgap until we can clean this up and separate out fpm-registry like crates.io to provide more info.

### CODE REVIEW

**Comment by LKedward** [comment]
#build_preview

**Comment by LKedward** [comment]
Sorry, preview's not working because it depends on the new CI files

**Comment by LKedward** [comment]
Thanks Ondřej! Yep I'm open to suggestions as to how we can improve this in the future

**Comment by LKedward** [comment]
#delete_preview

**Comment by certik** [comment]
I checked it on the website and it looks awesome! Thank you for implementing this.

**Pull request merged**
