### PR TITLE
fix dependency of include files under `learn/building_programs` mini-book

### PR DESCRIPTION
**Pull request by p-costa**
I had to do this fix to the dependencies generator, to be able to build a project in the case when the makefile is not in the same directory as the source files. I hope this makes sense!

### CODE REVIEW

**Comment by p-costa** [comment]
(I just noticed that I accidentally did not fork the project... I hope this is fine, else I can close and re-submit a proper PR)

**Review by awvwgk — APPROVED** [review]
Nice catch.

If you are on it already, could you mend the regex above to also include zeros? `[a-zA-Z][a-zA-Z0-9_]` instead of `[a-zA-Z][a-zA-Z1-9_]`?

**Comment by awvwgk** [comment]
I'm surprised this is actually used, I wrote this guide to show how involved the makefile setup can become and motivate people to use fpm or other high-level build systems with proper Fortran support ;).

**Comment by p-costa** [comment]
> I'm surprised this is actually used, I wrote this guide to show how involved the makefile setup can become and motivate people to use fpm or other high-level build systems with proper Fortran support ;).

*fpm* will come first for me! But I also want to update my naive build workflow using `make` with this nice and robust one.

**Pull request merged**
