### PR TITLE
Improve tags

### PR DESCRIPTION
**Pull request by jme52**
Assorted changes related to tags: ensure some multi-word tags are joined by hyphens, unify equivalent tags, fix typos in a couple of tags, add missing tags.

This PR partially addresses #176.

### CODE REVIEW

**Comment by LKedward** [comment]
#build_preview

**Review by LKedward — APPROVED** [review]
Looks good thanks!

**Review by awvwgk — APPROVED** [review]
Thanks, looks good to me.

**Comment by jme52** [comment]
Thank you.  Based on the updated tag cloud, I added a few more hyphens (and found a typo in the process).  I won't be making any further changes - you probably want to check the updated PR build, but unless something is broken there, as far as I am concerned this PR is ready to be merged.

**Comment by awvwgk** [comment]
#delete_preview

**Comment by Beliavsky** [comment]
Looking at 




qContainers | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp;
-- | -- | -- | -- | -- | -- | --
Store any intrinsic or derived data type to a container
Tags:&nbsp;qlibc tree table hash table linked list vector dynamic array unique set



I think there are still many multi-word tags that need to be hyphenated. I assume `hash-table`, `linked-list`, and `dynamic-array` are multi-word tags.

**Comment by ivan-pi** [comment]
@Beliavsky, mind opening a new issue for the multi-word tags?

**Pull request merged**
