### PR TITLE
Add SeisSol to package index

### PR DESCRIPTION
**Pull request by ashirrwad**
Added the SeisSol package listed on Issue: #232  to the package index.

### CODE REVIEW

**Review by milancurcic — APPROVED** [review]
Looks good to me. While at first this looked like a C++ project with Fortran bindings, on closer look it seems to be a mixed C++ and Fortran project.

We've had some discussions in the past whether Fortran bindings to a foreign-language project would be appropriate for the index. While I think they are, I don't think we've reached a consensus about it.

**Review by certik — APPROVED** [review]

**Comment by certik** [comment]
I also thought this is a C++ project with legacy Fortran, but it seems it has physics stuff in Fortran and it is still developed in Fortran (see e.g. https://github.com/SeisSol/SeisSol/pull/536), so I would say this package fits into our index.

(If it was just Fortran wrappers, then I would say we should have a category for Fortran wrappers to other packages.)

**Comment by ivan-pi** [comment]
For the record, the developers have told me they would like to remove Fortran soon. See also the comment here: https://github.com/fortran-lang/fortran-lang.org/issues/232#issuecomment-1099727757

**Comment by ashirrwad** [comment]
As the package was still a part of checklist on #232 and the library and its documentation showed references to Fortran usability I figured it was still up for addition. While I did stick to the [guide](https://github.com/fortran-lang/fortran-lang.org/blob/HEAD/PACKAGES.md) the criterias for package addition are a bit ambiguous to me as I am new to the language. If the package doesn't meet the requirements I will add a PR to revert these changes as needed.

**Pull request merged**
