### PR TITLE
Update package_index.yml

### PR DESCRIPTION
**Pull request by alinelena**
adding dl_poly_4 to the list of packages.

### CODE REVIEW

**Review by certik — CHANGES_REQUESTED** [review]
Here is the criteria that I am using to judge the PR: https://github.com/fortran-lang/fortran-lang.org/blob/master/PACKAGES.md

The package (https://gitlab.com/ccp5/dl-poly/) had 3 stars on GitLab, so I gave it a star. :)
I think it would satisfy the "star" requirement, as GitLab projects typically get less stars than GitHub ones.

However I think the README requirement is not satisfied:

> README: the package shall have some form of README or landing-page clearly stating the package purpose and functionality. This should also contain information on the package dependencies and the steps required to build and run.

What is the purpose of the package and the functionality? It currently does not say anything. Only from this PR I can see that it is a "classical MD". 

@alinelena would you mind please adding some brief paragraph into the README for your package to explain what it is, what features it has (if it is has some features that other classical MD packages don't have or if it is meant for teaching / learning), does it run in parallel, etc.?

Also, you should remove the space between `[Build instructions] (./building.md)` to make it a link in your README.

**Comment by alinelena** [comment]
@certik I can fix almost all the things you suggest... but the star stuff sorry I do not like to entertain that, it is really teenage stuff.

**Comment by certik** [comment]
@alinelena if you fix what I suggested, we will be happy to include your package. As I suggested, you do not have to worry about the number of stars. If you have a better idea how we could formulate the criteria, please let us know, we are open to suggestions.

**Comment by certik** [comment]
The README now gives an overview about the project:

https://gitlab.com/ccp5/dl-poly/-/blob/88a0c62d1cda8f50703c3d088396aba9e2c0a1e2/README.md

Moreover, it lists publications in CPC which describe details about the original code as well as recent publications.

**Comment by certik** [comment]
@alinelena would you mind please reopening this PR so that we can merge it?

**Comment by certik** [comment]
New PR was sent at #233.

**Pull request closed without merging**
