### PR TITLE
add the SNaC package ?

### PR DESCRIPTION
**Pull request by p-costa**
Hello everyone,

I wrote [SNaC](https://github.com/p-costa/SNaC), a multi-block finite-difference solver for massively parallel simulations of fluid flows. Despite being young and the low number of stars, I hope you find it interesting and suitable for integrating the list of scientific codes.

Thanks in advance!
Pedro

### CODE REVIEW

**Comment by certik** [comment]
Thanks @p-costa for submitting it! Is the "the primary functionality of the package" implemented? If so, then I think it should be included as far as I am concerned.

**Comment by p-costa** [comment]
Thanks, Ondřej @certik! Yes, it is definitely mature regarding the funtionality.

**Review by certik — APPROVED** [review]
+1 from me.

**Review by milancurcic — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
