### PR TITLE
Add missing packages from list of popular Fortran projects

### PR DESCRIPTION
**Pull request by awvwgk**
This should add *all* the remaining packages from https://github.com/fortran-lang/fortran-lang.org/issues/68 which have an open source license.

*Important:* since my background is electronic structure theory, I'm mostly not familiar with weather modeling or astrodynamics, which many of those projects are targeting. Somebody with experience in this fields should have a look over the descriptions and add tags as appropriate.

This PR will eventually close https://github.com/fortran-lang/fortran-lang.org/issues/68.

### CODE REVIEW

**Review by LKedward — APPROVED** [review]
Many thanks @awvwgk, this is great! All looks good to me :+1:

**Comment by awvwgk** [comment]
Let's try the #build_preview again.

**Review by certik — APPROVED** [review]
I think this looks great, thank you!

**Comment by awvwgk** [comment]
#delete_preview

**Pull request merged**
