### PR TITLE
Initial draft of october newsletter.

### PR DESCRIPTION
**Pull request by LKedward**
- [x] Make sure PRs are up-to-date on Thursday (@LKedward)
- [x] Update contributor data on Thursday (@LKedward)
- [x] Add news from Flang (@AlexisPerry)
- [x] Add news from lfortran (@certik
- [x] Add monthly meeting recording link (@milancurcic)

### CODE REVIEW

**Comment by LKedward** [comment]
@AlexisPerry & @certik, apologies for the late start this month - are you both able to provide the usual compiler updates in the next couple of days?

**Comment by AlexisPerry** [comment]
Yes, I'm planning to tackle it after the Flang biweekly meeting tomorrow so I can provide the most up to date information,

**Comment by AlexisPerry** [comment]
@LKedward  Check out the PR here: https://github.com/LKedward/fortran-lang.github.io/pull/5

**Comment by LKedward** [comment]
#build_preview

**Comment by certik** [comment]
#build_preview

**Comment by certik** [comment]
@LKedward I am done. Thanks!

**Comment by LKedward** [comment]
Many thanks everyone - I'll merge this later today

**Comment by LKedward** [comment]
#delete_preview

**Pull request merged**
