### PR TITLE
Change the name to HPE / Cray

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by milancurcic** [comment]
I think @longb mentioned on the call that they still use Cray for software products. Should we rather call this "Cray (HPE)". That way it's clear that it's what people know as Cray, while still acknowledging the parent company. Bill, how would you word this?

**Comment by milancurcic** [comment]
Otherwise, it's fine with me. My earlier comment is a super minor nit pick. We can always improve it later.

**Comment by certik** [comment]
I am going to merge it, and if Bill suggests a different wording, we'll change it.

I plan to contact each company anyway to approve the wording for their compiler, I just didn't have time yet.

**Comment by longb** [comment]
> On May 14, 2020, at 3:30 PM, Milan Curcic <notifications@github.com> wrote:
> 
> 
> I think @longb mentioned on the call that they still use Cray for software products.

Correct. As the page correctly indicates, the old HP compiler is not longer being maintained.  The Cray compilers are being ported to the more modern HPE hardware, such as Apollo. 


> Should we rather call this "Cray (HPE)". That way it's clear that it's what people know as Cray, while still acknowledging the parent company. Bill, how would you word this?

I’ll ask the manager in the know.  At least for Fortran, everyone still thinks of it as the “Cray compiler”.    However, “Cray” by itself (as a company) probably needs qualification. 

Cheers,
Bill

> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Bill Long                                                                       longb@cray.com
Principal Engineer, Fortran Technical Support &   voice:  651-605-9024
Bioinformatics Software Development                      fax:  651-605-9143
Cray, a Hewlett Packard Enterprise company/ 2131 Lindau Lane/  Suite 1000/  Bloomington, MN  55425

**Pull request merged**
