### PR TITLE
Add 2DECOMP&FFT to package index

### PR DESCRIPTION
**Pull request by ivan-pi**
Homepage: http://www.2decomp.org/

cc @ThemosTsikas, are there any tags (keywords) you'd like to see from NAG's perspective? (For more context, the aim the pull request is to add 2DECOMP to the [Fortran Package Index](https://fortran-lang.org/packages/) at fortran-lang.org; the criteria for a package to be indexed are specified [here](https://github.com/fortran-lang/fortran-lang.org/blob/master/PACKAGES.md))

Note that entries other than 2Decomp are handled in separate pull requests.

### CODE REVIEW

**Comment by p-costa** [comment]
I think that the 2decomp repo is also now hosted/archived on github, here: https://github.com/numericalalgorithmsgroup/2decomp_fft

**Comment by ivan-pi** [comment]
Thanks for the information. I guess I should reference the NAG GitHub page then. It's a shame there is no link to the original website though, it contains some nice material.

**Comment by p-costa** [comment]
Indeed... Maybe in the future, the list could also show the URL?

**Review by p-costa — APPROVED** [review]
Thanks Ivan, @ivan-pi ! Looks good, perhaps pending the edit w/ the 2DECOMP GitHub repo.

**Comment by ThemosTsikas** [comment]
I have now left NAG. If you need comment from NAG, you can use their support@ email address, care of Lawrence Mulholland.

**Review by milancurcic — APPROVED** [review]
Thank you!

**Pull request merged**
