### PR TITLE
fix canonical links for crawlers

### PR DESCRIPTION
**Pull request by henilp105**
This PR is to resolve https://github.com/fortran-lang/webpage/issues/222 , Please refer : https://fortran-lang.discourse.group/t/4942 .

This would add a custom canonical link tag to all the pages of the webpage.

Thanks and Regards,
Henil

CC @awvwgk @certik

### CODE REVIEW

**Comment by certik** [comment]
What will this change do exactly? Will it look like a duplicate?

**Comment by henilp105** [comment]
@certik this patch would show this deprecated site as a duplicate to webpage site , by adding a canonical link which points to the main webpage (shows  a search engine that this is the location of the original content and prioritise this link ).

**Comment by henilp105** [comment]
#build_preview

**Comment by certik** [comment]
Ok, let's try it!

**Pull request merged**
