### PR TITLE
Initial draft of the August newsletter

### PR DESCRIPTION
**Pull request by milancurcic**
* [x] Update contributors data (@LKedward)
* [ ] Flang updates (@AlexisPerry)
* [x] LFortran updates (@certik)
* [x] Ensure PRs are up to date at the end of the month (@milancurcic)

### CODE REVIEW

**Comment by milancurcic** [comment]
Just a friendly reminder that we aim to merge this on August 1. Thank you!

**Comment by LKedward** [comment]
Thanks for starting Milan! Looks good pending updates to the PRs.

**Comment by certik** [comment]
I will submit LFortran later today.

**Comment by certik** [comment]
I am still working on it.

**Review by certik — APPROVED** [review]
Ok, I am done with LFortran.

**Comment by certik** [comment]
@LKedward is there some documentation how you update the automatic contributor list? I know I wrote some initial scripts, but I think you might have some changes to those that you use, and I would like to learn and document how to do this.

**Comment by LKedward** [comment]
I don't think I've made any changes to the original scripts, so I'm just following the README as documentation. I can add something to our [Newsletter wiki page](https://github.com/fortran-lang/fortran-lang.org/wiki/Monthly-Newsletter), however the process needs to be moved into our CI - unfortunately I haven't had the time to do this quite yet.

**Comment by certik** [comment]
> I'm just following the README as documentation

This README: https://gitlab.com/fortran-lang/github_stats/-/blob/master/README.md or some other README?

**Comment by LKedward** [comment]
Yes that README. I just updated the Wiki page with some basic instructions.

**Comment by certik** [comment]
I see it now, awesome. We should improve the scripts more. For example, it seems we do not need to store the actual text of the comments. I stored initially everything, as I didn't know if we will need it, but it seems we don't (unless we wanted to count words, or something like that).

**Comment by milancurcic** [comment]
#build_preview

**Comment by milancurcic** [comment]
Thank you all, the newsletter looks good, I'll merge.

**Comment by milancurcic** [comment]
#delete_preview

**Comment by AlexisPerry** [comment]
Sorry I missed the last couple newsletters; I was out on maternity leave.  Will catch up on the Flang updates in the next one.

**Comment by certik** [comment]
@AlexisPerry no problem, thanks for letting us know and looking forward for the next month's update.

**Pull request merged**
