### PR TITLE
Add SLICOT to package index

### PR DESCRIPTION
**Pull request by ivan-pi**
Homepage: http://slicot.org/
GitHub: https://github.com/SLICOT/SLICOT-Reference

cc @andreasvarga - The Fortran Package Index (https://fortran-lang.org/packages/) provides a searchable index of Fortran software for various purposes. Adding SLICOT to the index would help both new and existing Fortran users to easily find the package. Would you be able to provide some tags (keywords) for the SLICOT library?

The conditions that need to be fulfilled for the package to be indexed are given here: https://github.com/fortran-lang/fortran-lang.org/blob/master/PACKAGES.md

Please note, this pull request only applied to SLICOT, the other new entries are handled in separate pull requests.

### CODE REVIEW

**Review by everythingfunctional — APPROVED** [review]
Seems like a welcome addition, and it looks like the info is accurate. :+1: from me.

**Comment by LKedward** [comment]
#build_preview

**Comment by andreasvarga** [comment]
I suggest the following keywords for SLICOT: 
fortran control-systems filtering system-identification system-analysis-and-design descriptor-systems periodic-systems  linear-algebra

**Review by milancurcic — APPROVED** [review]
Thank you!

**Pull request merged**
