### PR TITLE
Add incompact3d to package index

### PR DESCRIPTION
**Pull request by awvwgk**
See https://github.com/xcompact3d/Incompact3d

### CODE REVIEW

**Review by brocolis — APPROVED** [review]

**Review by milancurcic — APPROVED** [review]
Thanks!

**Comment by certik** [comment]
Looks good. I am happy to see codes like these in Fortran.

**Comment by awvwgk** [comment]
Found this one by following @fschuch from the recent stars at test-drive ;).

**Comment by certik** [comment]
Awesome. @fschuch, if you have any feedback on our efforts, please let us know!

**Pull request merged**
